{
    'name': 'IT Department',
    'version': '1.0.0',
    'summary': 'Centralized IT management for PT GSI – Site Wolo',
    'sequence': 1,
    'category': 'IT',
    'author': 'Azvan',
    'depends': ['base', 'product', 'hr', 'stock', 'web', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/master_data.xml',
        'views/asset_views.xml',
        'views/consumable_views.xml',
        'views/dashboard_views.xml',
        'views/asset_category_views.xml',
        'views/asset_assignment_views.xml',
        'views/asset_maintenance_views.xml',
        'views/asset_unit_category_views.xml',
        'views/asset_unit_views.xml',
        'views/printer_usage_views.xml',
        'report/asset_report.xml',
        'report/asset_report_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'it_asset/static/src/components/dashboard/dashboard.js',
            'it_asset/static/src/components/dashboard/dashboard.xml',
            'it_asset/static/src/components/dashboard/dashboard.scss',
        ],
        'web.assets_frontend': [
            'it_asset/static/src/scss/login_style.scss',
        ],
    },
    'installable': True,
    'application': True,
}
